### ISSUE TITLE
Some tips about making this code nicer

### ISSUE THREAD

**Issue by powerc9000** [krydge/SudoSpike#1]
So javascript has `classList` to manage what you are doing with class names here.

So you can do `classList.remove("active")` and `classList.add("active")` there is also `classList.toggle("active")` and it will manage it much nicer for you!.

```javascript
                  for (i = 0; i < dots.length; i++) {
                      dots[i].classList.remove("active");
                  }
                  slides[slideIndex-1].style.display = "block";  
                  dots[slideIndex-1].classList.add("active");
```

https://github.com/krydge/SudoSpike/blob/ada98687913038e701e28309e8ccf363845463af/Project%20sudoSpike/sudoSpike.html#L85

Exciting yo see you are learning javascript!

**Comment by krydge** [comment]
Thanks. i have done some other things with it before. The one i am most proud of is my piano one. Javascript is strange to work with.
